### ISSUE TITLE
what's the difference between MODEL_DIR and PRETRAINED_PATH in finetuning_assemble_on_food101.sh

### ISSUE THREAD

**Issue by endy-see** [clovaai/assembled-cnn#2]
Hi, I'm trying to finetuning on my own dataset, but I don't know how to write the run script, in your demo finetuning_assemble_on_food101.sh, there are two model path I had to provide, but from your README, I only get one pretrain model, which is Assemble-R50. I don't know how to provide a PRETRAINED_PATH, can you give me som suggestions? Thank you very much!

**Comment by sweaterr** [comment]
Hi, 

`PRETRAINED_PATH` is the path of checkpoint you downloaded.
`MODEL_DIR` is the output model path
