### ISSUE TITLE
The baseline performance of R50

### ISSUE THREAD

**Issue by pkuCactus** [clovaai/assembled-cnn#5]
Thanks for your great work. The baseline performance in Table 1,2,3 of paper are all 76.3, but in the Table 6,7,8, and 10 all are 76.87, waht is the difference of the baseline?

**Comment by norman3** [comment]
The learning rate decay is different.

- Table 1,2,3 : piecewise learning rate decay was used.
- Table 6,7,8,10 : cosine learning rate decay was used.

**Comment by pkuCactus** [comment]
I see, and thanks for you kindly reply.
