### ISSUE TITLE
Can you tell me how I should make my own data set to classify specific pictures

### ISSUE THREAD

**Issue by yc139464127** [clovaai/assembled-cnn#6]
I want to use it to classify my pictures

**Comment by sweaterr** [comment]
Hi,

To create your own training dataset, you need to convert it to TFRecord. For example this [code](https://github.com/clovaai/assembled-cnn/blob/master/datasets/build_fgvc_aircraft.py) is the code to convert [fgvc-aircraft data](http://www.robots.ox.ac.uk/~vgg/data/fgvc-aircraft) to tfrecord. 

Thanks
